###
POST http://localhost:8080/api/v1/word
Content-Type: application/json

{
  "groupId": 3,
  "name": "group",
  "definition": "группа"
}

###
PUT http://localhost:8080/api/v1/word/35
Content-Type: application/json

{
  "groupId": 3,
  "name": "group",
  "definition": "группа",
  "done": true
}
